### ISSUE TITLE
rake db:migrate during installation? :-/

### ISSUE THREAD

**Issue by foca** [srushti/goldberg#110]
What's the rationale for not including the `db/schema.rb` file, which should be the authoritative source for generating a database at any given point in time? This makes `rake db:setup` not work, and makes me an sad panda.

**Comment by srushti** [comment]
That's mainly due to @achamian's & @kaiwren's hesitation to check in any generated file. Having just talked it over now the only issue seems to be idiots making changes to schema.rb itself. I don't really want to make decisions defensively with that kind of situation in mind. I'll be checking it in now.
