### ISSUE TITLE
Capybara specs are failing some time on goldberg

### ISSUE THREAD

**Issue by sivagollapalli** [srushti/goldberg#155]
I am using headless gem to run my request specifications on goldberg. When I run specs on my local system all are passes. When it runs by the goldberg some request specs are failing. I didn't understand why it happens? Is this problem with goldberg or headless gem. Could you please help me?

**Comment by srushti** [comment]
This is not likely to have anything to do with Goldberg. If it's failing on your CI server, it will probably fail if you run the same command (as the one you have Goldberg running) all by itself. Try running it on the CI server itself but from the shell rather than through Goldberg and see what happens. Goldberg doesn't do anything more special than run the build command in a shell, so it won't be affecting anything to do with capybara specs.
