### ISSUE TITLE
bin/goldberg start broken

### ISSUE THREAD

**Issue by apolzon** [srushti/goldberg#71]
Really enjoying this terrific build server yall have been kind enough to release.

Following the setup instructions in the README, I was able to get the server up and working by using `rails s` to boot Goldberg.  If I boot it using `bin/goldberg start`, pages either never load, or errors are thrown (undefined method clear_active_connections! and an error related to page_cache).

I've tried editing the start script to explicitly use the mongrel server, which is what rails s would use, but it hasn't made any difference.  Additionally, the server will sometimes flat-out fail when trying to boot, which results in a goldberg.pid file which must be removed by hand as the stop script doesn't delete it if the process is not found.

Thanks!

OS: Snow Leopard
Using RVM, ruby-1.9.2-p180

**Comment by srushti** [comment]
Thanks, we appreciate the compliment, and I agree it's a terrific build server.
I'll take a look at the `start` issue and get back to you. To be honest, I've been doing most of my testing using `rails s` since it helps to look at the server output, and it's possible a bug snuck in. I'll let you know if I can reproduce it.

**Comment by achamian** [comment]
I am still looking into the issue

**Comment by srushti** [comment]
Would it make sense to switch the daemonising of `start` off? It'll basically start like a normal `rails s`. At least until we fix this issue.

**Comment by achamian** [comment]
starting rails server in development environment and daemon mode fails. 

This is due to 
<code>
Thread.start{Init.new.start_poller} if Rails.env == 'development'
</code>

I am still working on figuring out, why starting a new thread should make the daemon fail. In the mean while I have removed bin/goldberg start/stop falling back to 'rails server'

**Comment by lucasefe** [comment]
I have the same problem. Please, keep me posted! 

Lucas

**Comment by srushti** [comment]
We never updated this ticket. But, we've switched to suggesting you use the "rails s" command when we wish to start the server. 5650ad4b3fe2e68276ef1bcb1a0be23b862fe0ef
